# Generated by Django 4.2.23 on 2025-07-26 13:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
            ],
            options={
                'indexes': [models.Index(fields=['label'], name='api_wallet_label_612641_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['txid'], name='api_transac_txid_a6320a_idx'), models.Index(fields=['wallet'], name='api_transac_wallet__280e1b_idx'), models.Index(fields=['wallet', 'amount'], name='api_transac_wallet__552136_idx')],
            },
        ),
    ]
