# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # wait for Postgres ready
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      # point Django’s DATABASES['default'] at the service
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DATABASE_URL: postgres://postgres:password@localhost:5432/test_db
      # disable collecting static files or debugging concerns
      DEBUG: "False"

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run flake8
        run: |
          # Fails if any lint errors
          flake8 .

      - name: Run Django tests
        run: |
          python manage.py test
